import { useCallback, useEffect, useRef, useState, type CSSProperties } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowRight, BookOpen, Camera, Check, ExternalLink, Layers3, Menu, Plus, RotateCcw, Search, Settings2, TrendingUp, X } from 'lucide-react';
import DeckHome from '../components/DeckHome';
import SidebarDecks from '../components/SidebarDecks';
import { Heatmap } from '../components/Statistics';
import { CardFrame, Empty, ErrorNotice, Modal, Toggle } from '../components/ui';
import { useDiscardGuard } from '../components/useDiscardGuard';
import PhotoImport, { type PhotoImportDraft } from '../features/PhotoImport';
import { installButtonSoundFeedback, playSound, setSoundPreferences } from '../features/sound';
import { getTabTextColor } from '../features/themeContrast';
import type { Deck } from '../types';
import DemoEditor, { type CardDraft } from './DemoEditor';
import DemoStudy from './DemoStudy';
import { addCards, cardHtml, deckRows, DEMO_CARD_CSS, loadCollection, MAX_CARDS, removeDeck, sampleCollection, statistics, STORAGE_KEY, type DemoCollection } from './collection';
import '../components/tab-contrast.css';

const REPO='https://github.com/so-nagi/modoo-cards';
const GUIDE=`${REPO}/blob/codex/public-release/docs/SELF_HOSTING.ko.md`;
const tabs=[{id:'decks',label:'내 덱',english:'DECKS',icon:Layers3},{id:'add',label:'카드 추가',english:'ADD',icon:Plus},{id:'browse',label:'탐색',english:'BROWSE',icon:Search},{id:'stats',label:'기록',english:'STATS',icon:TrendingUp}] as const;
type View=typeof tabs[number]['id']|'study'|'settings';
type Dialog={kind:'deck'|'delete'|'empty'|'preview';deck?:Deck}|{kind:'photo'|'reset'|'guide'}|null;
const blankDraft=(deckId:number):CardDraft=>({deckId,kind:'basic',front:'',back:''});
function initial(){try{return loadCollection(localStorage.getItem(STORAGE_KEY));}catch{return sampleCollection();}}

export default function DemoApp(){
  const [collection,setCollection]=useState<DemoCollection>(initial),[view,setView]=useState<View>('decks'),[selected,setSelected]=useState<number|null>(1),[dialog,setDialog]=useState<Dialog>(null),[mobile,setMobile]=useState(false),[deckName,setDeckName]=useState(''),[error,setError]=useState(''),[storageError,setStorageError]=useState(''),[toast,setToast]=useState(''),[draft,setDraft]=useState<CardDraft>(()=>blankDraft(1)),[query,setQuery]=useState(''),[previewIndex,setPreviewIndex]=useState(0),[previewAnswer,setPreviewAnswer]=useState(false),[practiceVersion,setPracticeVersion]=useState(0);
  const photoDraft=useRef<PhotoImportDraft|null>(null),photoSaving=useRef(false),editorUiDirty=useRef(false),guard=useDiscardGuard();
  const decks=deckRows(collection),stats=statistics(collection),current=decks.find(deck=>deck.id===selected)||decks[0],settings=collection.settings;
  const dirty=!!(draft.front.trim()||draft.back.trim());
  const editorDirty=()=>dirty||editorUiDirty.current;
  useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(collection));setStorageError('');}catch{setStorageError('브라우저에 저장할 수 없습니다. 현재 탭에서는 체험할 수 있지만 닫으면 변경 내용이 사라집니다.');}},[collection]);
  useEffect(()=>{setSoundPreferences({enabled:settings.sounds,volume:settings.volume});},[settings.sounds,settings.volume]);
  useEffect(()=>installButtonSoundFeedback(),[]);
  useEffect(()=>{if(!toast)return;const timeout=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(timeout);},[toast]);
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(view==='add'&&editorDirty()||photoDraft.current?.photo||photoDraft.current?.pasted||photoDraft.current?.rows.length){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[view,dirty]);
  const go=(next:View)=>{
    if(next===view){setMobile(false);return;}
    guard.request(()=>{if(view==='add')setDraft(blankDraft(current?.id||0));if(next==='add')setDraft(blankDraft(current?.id||0));setView(next);setMobile(false);setError('');window.scrollTo({top:0});},view==='add'&&editorDirty());
  };
  const open=(next:Dialog)=>{
    guard.request(()=>{if(view==='add'&&editorDirty()){setDraft(blankDraft(current?.id||0));setView('decks');}setDialog(next);setError('');setMobile(false);if(next?.kind==='deck')setDeckName(next.deck?.name||'');if(next?.kind==='preview'){setPreviewIndex(0);setPreviewAnswer(false);}},view==='add'&&editorDirty());
  };
  const study=(deck=current)=>{if(!deck)return;setSelected(deck.id);setPracticeVersion(n=>n+1);go('study');};
  const previewCards=dialog?.kind==='preview'?collection.cards.filter(card=>card.deckId===dialog.deck?.id):[];
  const previewCard=previewCards[previewIndex];
  const closePhoto=()=>guard.request(()=>{photoDraft.current=null;setDialog(null);},!!photoDraft.current&&(!!photoDraft.current.photo||!!photoDraft.current.pasted.trim()||!!photoDraft.current.rawText.trim()||photoDraft.current.rows.length>0),photoSaving.current);
  const saveCard=()=>{try{const next=addCards(collection,draft.deckId,draft.kind,draft.front,draft.back);setCollection(next);setToast(`${next.cards.length-collection.cards.length}장의 카드를 저장했습니다.`);setDraft({...draft,front:'',back:''});setError('');playSound('save');}catch(cause){setError((cause as Error).message);}};
  const saveDeck=()=>{
    const name=deckName.trim();
    if(!name||name.length>100){setError('덱 이름은 1~100자로 입력하세요.');return;}
    if(collection.decks.some(deck=>deck.name===name&&deck.id!==(dialog?.kind==='deck'?dialog.deck?.id:undefined))){setError('같은 이름의 덱이 있습니다.');return;}
    if(dialog?.kind==='deck'&&dialog.deck){const id=dialog.deck.id;setCollection({...collection,decks:collection.decks.map(deck=>deck.id===id?{...deck,name}:deck)});}
    else{if(decks.length>=100){setError('데모에서는 최대 100개의 덱을 만들 수 있습니다.');return;}const id=Math.max(0,...decks.map(deck=>deck.id))+1;setCollection({...collection,decks:[...collection.decks,{id,name,favorite:false}]});setSelected(id);}
    setDialog(null);setError('');
  };
  const record=useCallback((cardId:number,rating:number)=>setCollection(value=>({...value,answers:[...value.answers,{cardId,rating,at:new Date().toISOString()}].slice(-2000)})),[]);
  const undoAnswer=useCallback(()=>setCollection(value=>({...value,answers:value.answers.slice(0,-1)})),[]);
  const exportData=()=>{
    const blob=new Blob([JSON.stringify(collection,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='modoo-cards-demo.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  };
  const filtered=collection.cards.filter(card=>`${card.front} ${card.back}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return <div className={`app-shell demo-shell skin-classic theme-${settings.theme}`} style={{'--accent':settings.accent,'--active-tab-text':getTabTextColor(settings),'--card-font-size':`${settings.cardFontSize}px`} as CSSProperties}>
    <header className="mobile-header"><button className="icon-button" aria-label="메뉴 열기" onClick={()=>setMobile(true)}><Menu size={20}/></button><strong>모두카드 <small>체험판</small></strong><button className="icon-button" aria-label="설정" onClick={()=>go('settings')}><Settings2 size={19}/></button></header>
    {mobile&&<button className="drawer-shade" aria-label="메뉴 닫기" onClick={()=>setMobile(false)}/>}
    <aside className={`left-sidebar ${mobile?'open':''}`}><button className="mobile-close icon-button" aria-label="메뉴 닫기" onClick={()=>setMobile(false)}><X size={18}/></button><div className="profile-block"><div className="avatar"><BookOpen size={23}/></div><strong>모두카드 체험판</strong><span>로그인 없이 · 이 브라우저에서</span></div><SidebarDecks decks={decks} selected={current?.id??null} onSelect={id=>{setSelected(id);go('decks');}} onNew={()=>open({kind:'deck'})}/><div className="sidebar-bottom"><button onClick={()=>open({kind:'photo'})}><Camera size={14}/> 사진·파일로 추가</button><button onClick={()=>go('settings')}><Settings2 size={14}/> 설정</button><button onClick={()=>open({kind:'reset'})}><RotateCcw size={14}/> 샘플 초기화</button><a href={GUIDE} target="_blank" rel="noreferrer">내 계정으로 설치 <ExternalLink size={12}/></a></div></aside>
    <main className="main-workspace"><div className="workspace-inner"><div className="workspace-topline"><span>모두카드 · 체험판</span><a href={GUIDE} target="_blank" rel="noreferrer">설치 안내 <ExternalLink size={11}/></a></div>
      <nav className="page-tabs" aria-label="페이지 탭">{tabs.map(tab=><button key={tab.id} className={view===tab.id||view==='study'&&tab.id==='decks'?'active':''} aria-current={view===tab.id?'page':undefined} onClick={()=>go(tab.id)}>{tab.english}</button>)}</nav>
      <div className="demo-notice"><span><strong>체험판</strong> 입력 자료는 이 브라우저에만 저장됩니다.</span><button className="text-button" onClick={()=>open({kind:'guide'})}>지원 기능</button></div>
      <section className="main-paper">{storageError&&<ErrorNotice error={storageError}/>} {error&&<ErrorNotice error={error}/>}
        {view==='decks'&&<DeckHome demo decks={decks} today={stats.today} selected={current?.id??null} date="샘플 덱으로 시작하기" favoritePending={[]} onSelect={setSelected} onStudy={study} onAdd={()=>go('add')} onPhoto={()=>open({kind:'photo'})} onNew={()=>open({kind:'deck'})} onFiles={()=>open({kind:'photo'})} onFiltered={()=>open({kind:'guide'})} onOptions={()=>open({kind:'guide'})} onRename={deck=>open({kind:'deck',deck})} onEdit={deck=>open({kind:'deck',deck})} onDelete={deck=>open({kind:'delete',deck})} onEmpty={deck=>open({kind:'empty',deck})} onPreview={deck=>open({kind:'preview',deck})} onFavorite={deck=>setCollection({...collection,decks:collection.decks.map(item=>item.id===deck.id?{...item,favorite:!item.favorite}:item)})} onFilterAction={async()=>{open({kind:'guide'});}}/>}
        {view==='study'&&current&&<DemoStudy key={`${current.id}-${practiceVersion}`} name={current.name} cards={collection.cards.filter(card=>card.deckId===current.id)} onAnswer={record} onUndo={undoAnswer} onBack={()=>go('decks')}/>}
        {view==='add'&&<DemoEditor decks={collection.decks} draft={draft} onChange={setDraft} onSave={saveCard} onUiDirty={value=>{editorUiDirty.current=value;}}/>}
        {view==='browse'&&<><div className="page-heading"><h1>카드 탐색</h1><span className="subtle">{collection.cards.length}장</span></div><input aria-label="카드 검색" placeholder="질문 또는 정답 검색" value={query} onChange={e=>setQuery(e.target.value)}/><div className="demo-card-list">{filtered.map(card=><button key={card.id} onClick={()=>{const deck=decks.find(item=>item.id===card.deckId)!;open({kind:'preview',deck});setPreviewIndex(collection.cards.filter(item=>item.deckId===deck.id).findIndex(item=>item.id===card.id));}}><span>{card.front}</span><small>{collection.decks.find(deck=>deck.id===card.deckId)?.name}</small><ArrowRight size={14}/></button>)}</div>{!filtered.length&&<Empty title="검색 결과가 없습니다"/>}</>}
        {view==='stats'&&<><div className="page-heading"><h1>체험 기록</h1><span className="subtle">이 브라우저의 기록</span></div><div className="stat-strip"><div><span>오늘 답변</span><strong>{stats.today}<small>회</small></strong></div><div><span>전체 답변</span><strong>{collection.answers.length}<small>회</small></strong></div><div><span>카드</span><strong>{collection.cards.length}<small>장</small></strong></div></div><section className="stats-section"><h2>답변한 날짜</h2><Heatmap stats={stats}/></section><section className="stats-section"><h2>답변 분포</h2><div className="ratings-chart">{stats.ratings.map(({rating,count})=><div key={rating}><span>{['다시','어려움','알맞음','쉬움'][rating-1]}</span><div><i style={{width:`${collection.answers.length?count/collection.answers.length*100:0}%`}}/></div><strong>{count}</strong></div>)}</div></section><p className="hint">체험 기록은 실제 Anki 복습 일정이나 정답률을 나타내지 않습니다.</p></>}
        {view==='settings'&&<><div className="page-heading"><h1>체험판 설정</h1><span className="subtle">클래식 스킨</span></div><div className="form-grid two"><label>화면 밝기<select value={settings.theme} onChange={e=>setCollection({...collection,settings:{...settings,theme:e.target.value as typeof settings.theme}})}><option value="light">라이트</option><option value="neutral">내추럴</option><option value="dark">다크</option></select></label><label>테마색<input className="demo-color" aria-label="테마색" type="color" value={settings.accent} onChange={e=>setCollection({...collection,settings:{...settings,accent:e.target.value}})}/></label></div><label className="field-label">카드 글자 크기 · {settings.cardFontSize}px<input aria-label="카드 글자 크기" type="range" min={14} max={40} value={settings.cardFontSize} onChange={e=>setCollection({...collection,settings:{...settings,cardFontSize:Number(e.target.value)}})}/></label><CardFrame html="observe<hr>관찰하다" css={DEMO_CARD_CSS} className="demo-settings-preview"/><Toggle label="클릭 효과음" description="Banana Split Lubed · 메뉴 이동과 정답 확인" checked={settings.sounds} onChange={sounds=>setCollection({...collection,settings:{...settings,sounds}})}/><label className="field-label">음량<input aria-label="효과음 음량" type="range" min={0} max={1} step={0.05} value={settings.volume} onChange={e=>setCollection({...collection,settings:{...settings,volume:Number(e.target.value)}})}/></label><div className="demo-setting-actions"><button disabled={!settings.sounds} onClick={()=>playSound('reveal')}>효과음 들어보기</button><button onClick={exportData}><ArrowDownToLine size={13}/> 체험 자료 저장 (JSON)</button><button onClick={()=>open({kind:'reset'})}><RotateCcw size={13}/> 샘플 초기화</button></div><p className="hint">JSON 파일은 체험 자료를 보관하는 용도입니다. Anki 가져오기 파일은 아닙니다.</p></>}
      </section><footer className="workspace-footnote"><span>체험판 · Anki 엔진 미사용</span><a href={REPO} target="_blank" rel="noreferrer">소스 코드 · AGPL-3.0</a></footer>
    </div></main>
    <aside className="right-sidebar"><div className="side-note"><span className="eyebrow">오늘 체험</span><strong>{stats.today}<small>회 답변</small></strong></div><div className="aside-memo"><h2>먼저 해보기</h2><p>샘플 덱에서 복습을 시작하거나 카드 추가 탭에서 직접 입력하세요.</p><button onClick={()=>go('add')}><Plus size={14}/> 카드 만들기</button></div><div className="aside-memo"><h2>내 자료로 사용하기</h2><p>Google 로그인과 기기 간 동기화는 자신의 Firebase·서버에 설치한 뒤 사용할 수 있습니다.</p><a href={GUIDE} target="_blank" rel="noreferrer">설치 안내 보기 <ExternalLink size={12}/></a></div><div className="aside-footer"><span>복습 단축키</span><p><kbd>Space</kbd> 정답 보기</p><p><kbd>1</kbd> <kbd>2</kbd> <kbd>3</kbd> <kbd>4</kbd> 답변 평가</p><p><kbd>Z</kbd> 되돌리기</p></div></aside>
    <nav className="bottom-nav" aria-label="모바일 탐색">{tabs.map(tab=><button key={tab.id} className={view===tab.id?'active':''} onClick={()=>go(tab.id)}><tab.icon size={18}/><span>{tab.label}</span></button>)}<button className={view==='settings'?'active':''} onClick={()=>go('settings')}><Settings2 size={18}/><span>설정</span></button></nav>
    {toast&&<div className="toast" role="status"><Check size={15}/>{toast}</div>}
    {dialog?.kind==='deck'&&<Modal title={dialog.deck?'덱 편집':'덱 만들기'} onClose={()=>guard.request(()=>setDialog(null),deckName!==(dialog.deck?.name||''))}><label className="field-label">덱 이름<input autoFocus maxLength={100} value={deckName} onChange={e=>setDeckName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')saveDeck();}}/></label><p className="hint">데모의 덱은 각각 독립된 목록으로 관리됩니다.</p>{error&&<ErrorNotice error={error}/>}<div className="form-footer"><button className="primary" onClick={saveDeck}>저장</button></div></Modal>}
    {(dialog?.kind==='delete'||dialog?.kind==='empty')&&<Modal title={dialog.kind==='delete'?'덱 삭제':'덱 비우기'} onClose={()=>setDialog(null)}><p>{dialog.deck?.name}의 {dialog.kind==='delete'?'덱과 카드':'카드'}를 삭제할까요?</p><p className="hint">이 브라우저의 체험 자료만 변경됩니다.</p><div className="form-footer"><button onClick={()=>setDialog(null)}>취소</button><button className="danger" onClick={()=>{setCollection(removeDeck(collection,dialog.deck!.id,dialog.kind==='empty'));setDialog(null);setView('decks');}}>삭제</button></div></Modal>}
    {dialog?.kind==='reset'&&<Modal title="체험 자료를 초기화할까요?" onClose={()=>setDialog(null)}><p>직접 추가한 카드와 체험 기록을 지우고 처음 샘플로 돌아갑니다.</p><div className="form-footer"><button onClick={exportData}>자료 먼저 저장</button><button onClick={()=>setDialog(null)}>취소</button><button className="danger" onClick={()=>{setCollection(sampleCollection());setSelected(1);setDraft(blankDraft(1));setView('decks');setDialog(null);setToast('샘플을 초기화했습니다.');}}>초기화</button></div></Modal>}
    {dialog?.kind==='preview'&&<Modal title="카드 미리보기" onClose={()=>setDialog(null)}>{previewCard?<><div className="section-heading"><span>{dialog.deck?.name}</span><span>{previewIndex+1} / {previewCards.length}</span></div><div className="demo-preview-tabs"><button aria-pressed={!previewAnswer} onClick={()=>setPreviewAnswer(false)}>앞면</button><button aria-pressed={previewAnswer} onClick={()=>setPreviewAnswer(true)}>뒷면</button></div><CardFrame html={cardHtml(previewCard,previewAnswer)} css={DEMO_CARD_CSS}/><div className="form-footer"><button aria-label="이전 카드" disabled={previewIndex===0} onClick={()=>{setPreviewIndex(n=>n-1);setPreviewAnswer(false);}}><ArrowLeft size={14}/></button><button aria-label="다음 카드" disabled={previewIndex===previewCards.length-1} onClick={()=>{setPreviewIndex(n=>n+1);setPreviewAnswer(false);}}><ArrowRight size={14}/></button></div></>:<Empty title="이 덱에는 카드가 없습니다"/>}</Modal>}
    {dialog?.kind==='photo'&&<Modal title="사진·파일에서 단어 가져오기" wide onClose={closePhoto}>{!current?<Empty title="먼저 덱을 만드세요"/>:<><p className="hint">사진 OCR은 이 브라우저에서 처리됩니다. 등록할 덱: {current.name} · 최대 {MAX_CARDS}장</p><PhotoImport demo initialDraft={photoDraft.current} onDraftChange={value=>{photoDraft.current=value;}} onSavingChange={value=>{photoSaving.current=value;}} onClose={closePhoto} onAnkiFile={()=>setError('APKG·COLPKG는 설치판에서 가져올 수 있습니다. 데모에는 사진, TSV, CSV를 사용하세요.')} onImport={async rows=>{let next=collection;for(const row of rows)next=addCards(next,current.id,'basic',row.word,row.meaning);setCollection(next);setToast(`${rows.length}장의 카드를 추가했습니다.`);}}/>{error&&<ErrorNotice error={error}/>}</>}</Modal>}
    {dialog?.kind==='guide'&&<Modal title="체험판에서 할 수 있는 일" onClose={()=>setDialog(null)}><ul className="demo-support"><li>덱 검색·중요 표시·목록과 갤러리 보기</li><li>기본 카드와 문장 빈칸 만들기, 카드 미리보기</li><li>샘플 이미지 가리기 카드 복습</li><li>사진 OCR, TSV·CSV 파일과 텍스트로 단어 등록</li><li>정답 보기·답변 평가·되돌리기, 글자 크기와 테마색 변경</li></ul><p>Google 로그인·동기화, Anki 복습 일정, 필터 덱, 이미지 가리기 편집, HTML 템플릿과 APKG 가져오기는 설치판에서 지원합니다.</p><p className="hint">체험 자료는 이 브라우저의 저장 공간에만 남습니다. 공용 기기라면 체험 후 샘플 초기화를 실행하세요. 읽어주기는 브라우저·운영체제의 음성 서비스를 사용합니다.</p><div className="form-footer"><a className="demo-install-link" href={GUIDE} target="_blank" rel="noreferrer">내 계정으로 설치하기 <ExternalLink size={13}/></a></div></Modal>}
    {guard.confirmation}
  </div>;
}
