import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDownUp, CheckSquare, ChevronDown, Columns3, Flag, Pencil, Search, SlidersHorizontal, Trash2, X } from 'lucide-react';
import { api } from '../api';
import { playSound } from '../features/sound';
import type { CardRow, Deck, Model } from '../types';
import NoteEditor from './NoteEditor';
import { useDiscardGuard } from './useDiscardGuard';
import { Busy, CardFrame, Empty, ErrorNotice, Modal, errorText, htmlText } from './ui';
import './deck-browser.css';

const optionalColumns=[['deckName','덱'],['modelName','노트 유형'],['interval','간격'],['reps','복습 횟수'],['lapses','실패 횟수'],['tags','태그']] as const;
export default function Browser({decks,models,onChange,initialQuery='',scopeDeck,onLeaveScope}:{decks:Deck[];models:Model[];onChange:()=>Promise<void>;initialQuery?:string;scopeDeck?:Deck;onLeaveScope?:()=>void}){
 const [query,setQuery]=useState(initialQuery),[search,setSearch]=useState(initialQuery),[rows,setRows]=useState<CardRow[]>([]),[total,setTotal]=useState(0),[selected,setSelected]=useState<number[]>([]),[active,setActive]=useState<CardRow|null>(null);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0),[editing,setEditing]=useState<CardRow|null>(null);
 const [columns,setColumns]=useState<string[]>(['deckName','interval','reps']),[showColumns,setShowColumns]=useState(false),[sort,setSort]=useState('front'),[ascending,setAscending]=useState(true),[showAdvanced,setShowAdvanced]=useState(false),[action,setAction]=useState(''),[value,setValue]=useState('1');
 const editingBusy=useRef(false),editingDirty=useRef(false),discardGuard=useDiscardGuard();
 const scopeDeckId=scopeDeck?.id;
 const closeEditing=()=>discardGuard.request(()=>{editingDirty.current=false;setEditing(null);},editingDirty.current,editingBusy.current);
 const leaveScope=()=>discardGuard.request(()=>{editingDirty.current=false;setEditing(null);onLeaveScope?.();},editingDirty.current,busy||editingBusy.current);
 useEffect(()=>{setQuery(initialQuery);setSearch(initialQuery);},[initialQuery,scopeDeckId]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setSelected([]);setActive(null);const scope=scopeDeckId===undefined?'':`&deckId=${scopeDeckId}`;api<{cards:CardRow[];total:number}>(`/cards?q=${encodeURIComponent(search)}&limit=500${scope}`,{signal:controller.signal}).then(result=>{if(!controller.signal.aborted){setRows(result.cards);setTotal(result.total);}}).catch(err=>{if(!controller.signal.aborted){setRows([]);setTotal(0);setError(errorText(err));}}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[search,revision,scopeDeckId]);
 const ordered=useMemo(()=>[...rows].sort((a,b)=>{let x=a[sort as keyof CardRow],y=b[sort as keyof CardRow];if(sort==='front'){x=htmlText(a.front);y=htmlText(b.front);}const n=typeof x==='number'&&typeof y==='number'?x-y:String(x||'').localeCompare(String(y||''),'ko');return ascending?n:-n;}),[rows,sort,ascending]);
 const submit=()=>{setSearch(query);setRevision(n=>n+1);playSound('tap');};
 const quick=(part:string)=>{setQuery(part);setSearch(part);setRevision(n=>n+1);};
 const mutate=async(kind:string)=>{if(!selected.length||busy)return;setBusy(true);setError('');try{await api('/cards/action',{method:'POST',body:JSON.stringify({ids:selected,action:kind,...(['due','flag'].includes(kind)?{value:kind==='flag'?Number(value):value}:{})})});setAction('');setRevision(n=>n+1);await onChange();playSound(kind==='delete'?'delete':'save');}catch(err){setError(errorText(err));}finally{setBusy(false);}};
 const header=(key:string,label:string)=><button className="table-sort" onClick={()=>{setSort(key);setAscending(sort===key?!ascending:true);}}>{label}{sort===key&&<ArrowDownUp size={11}/>}</button>;
 const showCard=async(row:CardRow)=>{setActive(row);try{const detail=await api<CardRow>(`/cards/${row.id}`);setActive(current=>current?.id===row.id?detail:current);}catch(err){setError(errorText(err));}};
 return <div className="browser-view"><div className="page-heading"><div><h1>{scopeDeck?'덱 카드 편집':'카드 탐색'}</h1></div><span className="subtle">{total.toLocaleString()}장</span></div>{scopeDeck&&<div className="deck-browser-scope" aria-label="카드 검색 범위"><div><strong>{scopeDeck.name}</strong><span>하위 덱 포함</span></div>{onLeaveScope&&<button type="button" onClick={leaveScope} disabled={busy||!!action}>전체 덱 보기</button>}</div>}<form className="search-form" onSubmit={e=>{e.preventDefault();submit();}}><Search size={16}/><input aria-label="카드 검색" placeholder={scopeDeck?'이 덱에서 단어, 태그 또는 is:due 검색':'단어, 태그 또는 deck:"영어" is:due'} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button type="button" aria-label="검색어 지우기" onClick={()=>quick('')}><X size={14}/></button>}<button className="primary" type="submit">검색</button></form><div className="browser-toolbar"><div className="quick-filters"><button onClick={()=>quick('')}>전체</button><button onClick={()=>quick('is:due')}>복습 예정</button><button onClick={()=>quick('is:new')}>새 카드</button><button onClick={()=>quick('is:suspended')}>중단</button><button onClick={()=>quick('flag:1')}><Flag size={11}/> 표시</button></div><button aria-expanded={showAdvanced} onClick={()=>setShowAdvanced(!showAdvanced)}><SlidersHorizontal size={14}/> 검색식</button><button aria-expanded={showColumns} onClick={()=>setShowColumns(!showColumns)}><Columns3 size={14}/> 열</button></div>
 {showAdvanced&&<div className="inset-panel"><p>공식 안키 검색식으로 컬렉션을 찾을 수 있어요.</p><div className="query-examples">{['deck:"영어"','tag:시험','is:due','added:7','prop:lapses>3','-is:suspended'].map(example=><button key={example} onClick={()=>setQuery(current=>`${current} ${example}`.trim())}><code>{example}</code></button>)}</div><p className="fine-print">필드 이름:내용 · 여러 조건은 공백으로 연결 · OR와 괄호 지원</p></div>}
 {showColumns&&<div className="column-picker">{optionalColumns.map(([key,label])=><label key={key}><input type="checkbox" checked={columns.includes(key)} onChange={()=>setColumns(list=>list.includes(key)?list.filter(v=>v!==key):[...list,key])}/>{label}</label>)}</div>}
 {selected.length>0&&<div className="selection-bar"><span><CheckSquare size={14}/>{selected.length}장 선택</span><select aria-label="선택한 카드 작업" value="" onChange={e=>{const next=e.target.value;if(['delete','due','flag','reset'].includes(next))setAction(next);else void mutate(next);}} disabled={busy}><option value="">일괄 작업 선택</option><option value="suspend">학습 중단</option><option value="unsuspend">중단 해제</option><option value="bury">오늘 숨기기</option><option value="unbury">숨김 해제</option><option value="flag">깃발 변경</option><option value="due">복습 날짜 지정</option><option value="reset">새 카드로 초기화</option><option value="delete">삭제</option></select><button onClick={()=>setSelected([])}>선택 해제</button></div>}
 {error&&<ErrorNotice error={error} onRetry={()=>setRevision(n=>n+1)}/>}{loading?<Busy/>:!rows.length?<Empty icon={<Search size={27}/>} title="검색 결과 없음">검색 조건을 변경하거나 카드를 추가하세요.</Empty>:<div className="table-scroll"><table className="cards-table"><thead><tr><th><input type="checkbox" aria-label="표의 카드 전체 선택" checked={!!rows.length&&selected.length===rows.length} onChange={e=>setSelected(e.target.checked?rows.map(row=>row.id):[])}/></th><th>{header('front','앞면')}</th>{optionalColumns.filter(([key])=>columns.includes(key)).map(([key,label])=><th key={key}>{header(key,label)}</th>)}<th>상태</th><th/></tr></thead><tbody>{ordered.map(row=><tr key={row.id} className={active?.id===row.id?'active':''}><td><input type="checkbox" aria-label={`${htmlText(row.front).slice(0,30)} 선택`} checked={selected.includes(row.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,row.id]:ids.filter(id=>id!==row.id))}/></td><td><button className="card-cell" onClick={()=>void showCard(row)}>{row.flag>0&&<Flag size={12} className={`flag-color-${row.flag}`}/>}<span>{htmlText(row.front)||'(이미지·미디어 카드)'}</span></button></td>{optionalColumns.filter(([key])=>columns.includes(key)).map(([key])=><td key={key}>{key==='tags'?row.tags.join(', '):key==='interval'?`${row.interval}일`:String(row[key])}</td>)}<td><span className={`status-dot queue-${row.queue}`}/>{row.queue===-1?'중단':row.queue<0?'숨김':row.queue===0?'신규':row.queue===2?'복습':'학습'}</td><td><button className="icon-button" aria-label="노트 편집" onClick={()=>setEditing(row)}><Pencil size={13}/></button></td></tr>)}</tbody></table></div>}
 {total>rows.length&&<p className="hint">{total.toLocaleString()}장 중 처음 {rows.length}장을 표시해요. 검색 조건을 추가하면 나머지 카드를 찾을 수 있어요.</p>}
 {active&&<section className="browser-preview"><div className="section-heading"><h2>카드 미리보기</h2><button className="icon-button" aria-label="미리보기 닫기" onClick={()=>setActive(null)}><X size={15}/></button></div><div className="preview-columns"><CardFrame html={active.front} css={active.css} title="앞면 미리보기"/><CardFrame html={active.back} css={active.css} title="뒷면 미리보기"/></div><dl className="card-detail"><div><dt>간격</dt><dd>{active.interval}일</dd></div><div><dt>복습</dt><dd>{active.reps}회</dd></div><div><dt>실패</dt><dd>{active.lapses}회</dd></div><div><dt>노트 ID</dt><dd>{active.noteId}</dd></div></dl>{active.history&&<details><summary>복습 기록 {active.history.length}개</summary><pre className="history-json">{JSON.stringify(active.history,null,2)}</pre></details>}</section>}
 {discardGuard.confirmation}
 {editing&&<Modal title="노트 편집" wide onClose={closeEditing}><NoteEditor decks={decks} models={models} editing={editing} onClose={closeEditing} onSavingChange={saving=>{editingBusy.current=saving;}} onDirtyChange={dirty=>{editingDirty.current=dirty;}} onSaved={async()=>{setRevision(n=>n+1);await onChange();}}/></Modal>}
 {action&&<Modal title={{delete:'선택한 카드 삭제',due:'복습 날짜 지정',flag:'깃발 변경',reset:'새 카드로 초기화'}[action]||'카드 작업'} onClose={()=>setAction('')}><p>{selected.length}장의 카드를 변경해요.</p>{action==='delete'&&<p className="hint">같은 노트에서 만들어진 형제 카드도 함께 삭제될 수 있어요. 자료가 필요하다면 먼저 내보내기로 보관하세요.</p>}{action==='reset'&&<p className="hint">현재 복습 일정을 해제하고 새 카드 상태로 되돌려요.</p>}{action==='due'&&<label className="field-label">오늘부터 며칠 후에 복습할까요?<input value={value} onChange={e=>setValue(e.target.value)} placeholder="1 또는 3-7"/><small>0은 오늘, 3-7은 3~7일 사이에 나누어 배치</small></label>}{action==='flag'&&<label className="field-label">깃발<select value={value} onChange={e=>setValue(e.target.value)}><option value="0">표시 없음</option><option value="1">빨강</option><option value="2">주황</option><option value="3">초록</option><option value="4">파랑</option><option value="5">분홍</option><option value="6">청록</option><option value="7">보라</option></select></label>}<div className="form-footer"><button onClick={()=>setAction('')}>취소</button><button className={action==='delete'?'danger':'primary'} disabled={busy} onClick={()=>void mutate(action)}>{busy?'처리 중…':'적용'}</button></div></Modal>}
 </div>;
}


