import { useMemo } from 'react';
import type { Stats } from '../types';

function localDate(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
export function Heatmap({stats,compact=false}:{stats:Stats;compact?:boolean}){
 const days=useMemo(()=>{const map=new Map(stats.history.map(day=>[day.date,day.count]));const today=new Date();const length=compact?91:182;return Array.from({length},(_,index)=>{const date=new Date(today);date.setDate(date.getDate()-length+index+1);const key=localDate(date);return{date:key,count:map.get(key)||0};});},[stats.history,compact]);
 const max=Math.max(1,...days.map(day=>day.count));return <div className={`heatmap-block ${compact?'compact':''}`}><div className="heatmap" aria-label="날짜별 복습 횟수">{days.map(day=><span key={day.date} title={`${day.date} · ${day.count}회 복습`} aria-label={`${day.date} ${day.count}회`} className={`heat-level-${day.count?Math.min(4,Math.ceil(day.count/max*4)):0}`}/>)}</div><div className="heatmap-legend"><span>{compact?'지난 3개월':'지난 6개월'}의 기록</span><span>적음 <i className="heat-level-0"/><i className="heat-level-1"/><i className="heat-level-2"/><i className="heat-level-3"/><i className="heat-level-4"/> 많음</span></div></div>;
}
export default function Statistics({stats}:{stats:Stats}){
 const totalRatings=stats.ratings.reduce((n,item)=>n+item.count,0);const forecastMax=Math.max(1,...stats.forecast.map(day=>day.count));const total=Math.max(1,stats.totalCards);
 return <div className="stats-view"><div className="page-heading"><div><h1>학습 기록</h1></div><span className="subtle">컬렉션 전체</span></div><div className="stat-strip"><div><span>오늘 복습</span><strong>{stats.today}<small>회</small></strong></div><div><span>연속 학습</span><strong>{stats.streak}<small>일</small></strong></div><div><span>오늘 학습 시간</span><strong>{Math.round(stats.reviewTime/60000)}<small>분</small></strong></div><div><span>정답률</span><strong>{Math.round(stats.retention)}<small>%</small></strong></div></div><section className="stats-section"><div className="section-heading"><h2>날짜별 복습 횟수</h2><span className="subtle">Review Heatmap</span></div><Heatmap stats={stats}/></section><section className="stats-section"><div className="section-heading"><h2>복습 예정</h2><span className="subtle">예정 카드</span></div>{!stats.forecast.length?<p className="quiet-empty">아직 예약된 복습이 없어요.</p>:<div className="forecast">{stats.forecast.slice(0,30).map((day,index)=><div className="forecast-column" key={day.date} title={`${day.date}: ${day.count}장`}><div className="forecast-track"><span style={{height:`${Math.max(0,day.count/forecastMax*100)}%`}}/></div><small>{index%5===0?day.date.slice(5):''}</small></div>)}</div>}</section><div className="stats-bottom"><section className="stats-section"><h2>내 컬렉션</h2><p className="subtle">노트 {stats.totalNotes.toLocaleString()}개 · 카드 {stats.totalCards.toLocaleString()}장</p><div className="distribution-bar">{(['new','learn','review','suspended'] as const).map(key=><span key={key} className={`dist-${key}`} style={{width:`${stats.counts[key]/total*100}%`}}/>)}</div><dl className="collection-counts">{([['new','새 카드'],['learn','학습 중'],['review','복습'],['suspended','중단']] as const).map(([key,label])=><div key={key}><dt><i className={`dist-${key}`}/>{label}</dt><dd>{stats.counts[key].toLocaleString()}</dd></div>)}</dl></section><section className="stats-section"><h2>답변 분포</h2><p className="subtle">기록된 답변 {totalRatings.toLocaleString()}회</p><div className="ratings-chart">{[1,2,3,4].map(rating=>{const count=stats.ratings.find(item=>item.rating===rating)?.count||0;return <div key={rating}><span>{['다시','어려움','알맞음','쉬움'][rating-1]}</span><div><i style={{width:`${totalRatings?count/totalRatings*100:0}%`}}/></div><strong>{count}</strong></div>;})}</div></section></div></div>;
}



